### ISSUE TITLE
Unable to sync playback progress.

### ISSUE THREAD

**Issue by countott** [Plex-External-Player-PotPlayer/Extension#1]
The script works flowlessly, thx for the effort.
However the playback sync is not working.
The potplayer already detected the Extensions.
![image](https://user-images.githubusercontent.com/74023119/137442657-bee55a84-1811-45b1-bbc8-5860e929246e.png)

**Comment by countott** [comment]
![image](https://user-images.githubusercontent.com/74023119/137444842-9e44cd04-6eb5-4f6d-9466-770c02a1a4ee.png)
Plex server shows up downloading instead of normal streaming.

**Comment by Relax-87** [comment]
Sorry for not replying in time due to busy work

**Comment by Relax-87** [comment]
The project is currently discontinued
